### PR TITLE
Updated templates to work with ghost 1.0

### PR DESCRIPTION
**Pull request by wassimseif**
This should be done on a different branch because it won't work with all ghost version < 1.0

### CODE REVIEW

**Comment by Kikobeats** [comment]
Can you make Travis build pass on green? thanks 😄

**Comment by wassimseif** [comment]
The travis error (I Think) is not related to the changes i made. it's something related to a 404 on  `https://carlbernardo.github.io` please correct me if i'm wrong

**Comment by Kikobeats** [comment]
You r'e right, if you remove the 404 link to pass en green we can maintain the project up to date

**Comment by wassimseif** [comment]
Done

**Comment by Kikobeats** [comment]
Thanks! Released at  `2.9.5`

**Pull request merged**
