### PR TITLE
fixed sass compile error

### PR DESCRIPTION
**Pull request by Huanzhang89**
should use @include not @extend inside a mixin

### CODE REVIEW

**Comment by Kikobeats** [comment]
Can you paste your error? I don't see a syntax problem here. Extend works with include:

https://gist.github.com/roytomeij/6086923#file-extend-scss

also works fine in my local compilation :/

**Comment by Kikobeats** [comment]
also mi local compilation works fine :/

**Comment by Huanzhang89** [comment]
Sure thing I will show you on Tuesday. Left my macbook at work.

**Comment by Huanzhang89** [comment]
```
[10:26:31] { [Error: assets/scss/modules/_utils.scss
Error: ".navigation.left .links > li.expanded" failed to @extend "btn-cover".
       The selector "btn-cover" was not found.
       Use "@extend btn-cover !optional" if the extend should be able to fail.
        on line 56 of assets/scss/modules/_utils.scss
>>   @extend btn-cover;
   --^
]
  formatted: 'Error: ".navigation.left .links > li.expanded" failed to @extend "btn-cover".\n       The selector "btn-cover" was not found.\n       Use "@extend btn-cover !optional" if the extend should be able to fail.\n        on line 56 of assets/scss/modules/_utils.scss\n>>   @extend btn-cover;\n   --^\n',
  message: 'assets/scss/modules/_utils.scss\nError: ".navigation.left .links > li.expanded" failed to @extend "btn-cover".\n       The selector "btn-cover" was not found.\n       Use "@extend btn-cover !optional" if the extend should be able to fail.\n        on line 56 of assets/scss/modules/_utils.scss\n>>   @extend btn-cover;\n   --^\n',
  column: 3,
  line: 56,
  file: '/Users/huanzhang/bitbucket/mystuff/ghostblog/content/themes/uno-zen/assets/scss/modules/_utils.scss',
  status: 1,
  messageFormatted: '\u001b[4massets/scss/modules/_utils.scss\u001b[24m\nError: ".navigation.left .links > li.expanded" failed to @extend "btn-cover".\n       The selector "btn-cover" was not found.\n       Use "@extend btn-cover !optional" if the extend should be able to fail.\n        on line 56 of assets/scss/modules/_utils.scss\n>>   @extend btn-cover;\n   --^\n',
  messageOriginal: '".navigation.left .links > li.expanded" failed to @extend "btn-cover".\nThe selector "btn-cover" was not found.\nUse "@extend btn-cover !optional" if the extend should be able to fail.',
  relativePath: 'assets/scss/modules/_utils.scss',
  name: 'Error',
  stack: 'Error: assets/scss/modules/_utils.scss\nError: ".navigation.left .links > li.expanded" failed to @extend "btn-cover".\n       The selector "btn-cover" was not found.\n       Use "@extend btn-cover !optional" if the extend should be able to fail.\n        on line 56 of assets/scss/modules/_utils.scss\n>>   @extend btn-cover;\n   --^\n\n  at options.error (/Users/huanzhang/bitbucket/mystuff/ghostblog/content/themes/uno-zen/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:271:32)\n',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
```

**Comment by Huanzhang89** [comment]
as you can see @extend is looking for a selector, but btn-cover is a mixin not a selector. Therefore the compile fails. 

Using @include solves this problem.

**Comment by Kikobeats** [comment]
@Huanzhang89 But the point is that `%btn-cover` is not a mixin, it's a extend!

can you try do `rm -rf node_modules && npm install`?

For me is working perfectly:

```
❯ gulp css
[12:03:01] Requiring external module coffee-script/register
[12:03:04] Using gulpfile ~/Uno/gulpfile.coffee
[12:03:04] Starting 'css'...
[12:03:04] Finished 'css' after 23 ms
```

**Comment by Huanzhang89** [comment]
Pretty sure btn-cover is defined as a mixin

```
@mixin btn-cover {
  position: relative;

  display: block;

  font-size: .9em;
  -webkit-font-smoothing: antialiased;
  font-weight: bold;

  letter-spacing: 1px;

  opacity: .8;
  color: $gray-lightest;
  border-radius: 20px;
  text-shadow: none;

  &:hover {
    opacity: 1;
  }
}

@mixin btn-cover-with-border {
  @include btn-cover;
  border: 1px solid $gray-lightest;
}
```

**Comment by Huanzhang89** [comment]
maybe you made some changes to your local branch and didn't push?

**Comment by Kikobeats** [comment]
check this: https://github.com/Kikobeats/uno-zen/blob/master/assets/scss/modules/_utils.scss#L34

I think that you changed your codebase in your fork and then you did a merge and you resolved conflicts but this was erroneous solved.

**Comment by Huanzhang89** [comment]
ah I see, you updated this 8 days ago :)

I'll pull latest and try again

**Comment by Huanzhang89** [comment]
The update.sh script doesn't seem to work 

```
 _   _  _   _  _____    ______ _____  _   _
| | | || \ | ||  _  |  |___  /|  ___|| \ | |
| | | ||  \| || | | |     / / | |__  |  \| |
| | | || . ` || | | |    / /  |  __| | . ` |
| |_| || |\  |\ \_/ /  ./ /___| |___ | |\  |
 \___/ \_| \_/ \___/   \_____/\____/ \_| \_/

usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
fatal: No names found, cannot describe anything.
Current version: .
Searching for updates...
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
fatal: No names found, cannot describe anything.

You already have the latest version.

```

**Comment by Kikobeats** [comment]
Ok, then we can check update script. But it's a different problem 😄 .

Go conversation to https://github.com/Kikobeats/uno-zen/issues/199

**Pull request closed without merging**
