### PR TITLE
Local timezones

### PR DESCRIPTION
**Pull request by jefflau**

### CODE REVIEW

**Comment by Kikobeats** [comment]
before:

screen shot 2016-05-28 at 11 37 19

after:

screen shot 2016-05-28 at 11 37 25

Why do you prefer this horrible and non human friendly format?

**Comment by jefflau** [comment]
That's weird. Mine doesn't do that. Are there any errors?

screen shot 2016-05-28 at 17 48 47

**Comment by Kikobeats** [comment]
@jefflau lol, your screen is how it looks in my browser using the current codebase. what browser are you using?

**Comment by jefflau** [comment]
Chrome on Mac OSX

**Comment by Kikobeats** [comment]
hmmm try change only this line on `index.hbs`:

```
    <time datetime="{{date format="DD MMM YYYY"}}">{{date format="DD MMM YYYY"}}</time>
```

**Comment by jefflau** [comment]
That shouldn't make a difference, because I have change out the data anyway, because I change it to the local timezone and then onHover switch it to the new local date. You can see the code here:

``` coffeescript
localFormatted =
        day: localPostDate.getDate()
        month:localPostDate.getMonth()
        year: localPostDate.getFullYear()

      $(this).html(postDateInDays)
      $(this).mouseover -> $(this).html localFormatted.day + " " + monthNames[localFormatted.month] + " " + localFormatted.year
      $(this).mouseout -> $(this).html postDateInDays
```

Something weird is going on.

**Comment by Kikobeats** [comment]
hmm what version of ghost are you using? I think that is more a Ghost problem, try updating to 0.8 and test again with the current codebase

**Comment by jefflau** [comment]
Are you sure you're not using my old pull request or something? Can you try deleting the whole theme and redownloading my branch? When I was trying to edit your theme I was trying to rename your theme so I could reference the old version so I could redo the git commits for you, but ghost was being funky and still using the old version. Could be related?

**Comment by jefflau** [comment]
I'm on the latest version of Ghost for sure, I just downloaded it yesterday, so as you can see the post is 28 May 2016

**Comment by Kikobeats** [comment]
let's check how the date is format in other uno-zen installation:

http://binaryfever.com/#open
http://joshmiramant.com/#open

I see the date format correctly, paste an screen how do you see it please!

**Comment by jefflau** [comment]
screen shot 2016-05-28 at 18 11 46
screen shot 2016-05-28 at 18 11 37

Look fine to me.

**Comment by Kikobeats** [comment]
so this confirm the the current codebase output correctly the date following the format, are you right?

**Comment by jefflau** [comment]
Can you try deleting my theme and recloning it to check again?

**Comment by Kikobeats** [comment]
@jefflau what is the sense of that?

I mean, if this guys are running the current codebase and the date looks good, maybe we have to consider a particular problem in your installation (I don't know why, but as you can see, the problem don't appear in the rest of Uno installation).

For me is not easy "delete a clone again" because I have different branch in the local repository and more stuff.

Maybe a third person can confirm what happens.

**Comment by jefflau** [comment]
I'm telling you the problem may be appearing because of my old pull request and it didn't update properly.  Just delete the branch and then repull my branch instead of recloning it. Or you can do what I did and just create a fresh install of ghost and clone my repo in.  I have seen that problem when I did my last pull request and I spent the time to make sure it was right. I'm 100% that it's not to do with my installation of ghost, it's just an old version of my pull request that was in your repo. It was my fault that the bug appeared, but I've fixed it. If you don't want my commit that's fine, but I don't appreciate your constant sarcastic undertone when I'm just trying to help out.

**Comment by Kikobeats** [comment]
@jefflau but please I want to resolve this to know what happens, feel free to reply this PR or open another issue!

**Pull request closed without merging**
