### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jmiramant**
Included website in examples section. TY!

### CODE REVIEW

**Comment by jmiramant** [comment]
Added my website to the showcase manifest.Thanks!

**Comment by Kikobeats** [comment]
wow, it looks terribly awesome!

Could be possible create a PR with your cover changes? I want to apply in the codebase 😄

**Comment by jmiramant** [comment]
I'd be happy to. It was a joy working in your codebase. Let me clean it up and I'll create the PR. Thanks again!

**Comment by Kikobeats** [comment]
@jmiramant if you need any kind of help contact me using this issue or my email in my github account!

**Pull request merged**
