### PR TITLE
Restore custom cover

### PR DESCRIPTION
**Pull request by h4t0n**
The blog admin can use a custom cover (the image uploaded by the user in the blog admin area).

### CODE REVIEW

**Comment by Kikobeats** [comment]
Awesome!

Check [this](https://github.com/Kikobeats/uno-zen/blob/master/assets/scss/modules/_mixins.scss#L1-L4). Can you adapt it for use the Admin background but apply the linear gradient filter?

I was to setup the background from the filesystem because I didn't find a way to two both things but using ghost admin theme. Check [this question in stackoverflow](https://stackoverflow.com/questions/2504071/is-it-possible-to-combine-a-background-image-and-css3-gradients) as well.

**Comment by h4t0n** [comment]
I changed only the _background-image_ (not the _background_)... So it should not change others already defined css styles... but I'm not familiar wit sass, or css filters..  you should check it...

**Comment by h4t0n** [comment]
The problem is that you use sass colors variables inside the linear gradient filter... while my code simply replaces your backgroud image with the one coming from the ghost admin area.. It think it is better to use the custom image without any other css filter... This fits exactly my needs for my blog..

**Comment by Kikobeats** [comment]
I was working on this yesterday and and nothing has changed. background URL is in the ghost template and colors variables is in sass. The solution to combine both values is too complex, doing black magic with javascript. 

Change your background from `assets/img/cover.jpg`. I know that is a little creepy solution, but is the most easy and clear solution.

**Pull request closed without merging**
