### PR TITLE
Ghost error to replace few key names

### PR DESCRIPTION
**Pull request by robincsamuel**
Fixed errors and warnings.

### CODE REVIEW

**Comment by robincsamuel** [comment]
Will solve the issues #218 #219 #220 #221 #222 #223.

**Comment by Kikobeats** [comment]
Thanks!

**Comment by robincsamuel** [comment]
:) I noticed few more URLs in showcase file failing the checks.

**Comment by waja** [comment]
I think this changes makes the theme incompatible with ghost versions < 1.0.

**Comment by Kikobeats** [comment]
That's true; I would have to be released as major version.

What to do now? 🤔

**Comment by waja** [comment]
Create a 0.11 branch at least?

**Pull request merged**
