### PR TITLE
Updated overflow for content

### PR DESCRIPTION
**Pull request by robincsamuel**
Content scroll was visible on top of cover. Added condition to hide overflow if cover is expanded.

### CODE REVIEW

**Comment by Kikobeats** [comment]
which browser and which version are you using?

Can you post a gif of the before and after?

**Comment by robincsamuel** [comment]
Ya sure! Actually am on a mac and its already fine. Its weird on linux/windows. I'll try to get screens asap.

-----Original Message-----

**Comment by robincsamuel** [comment]
Before
image

After
image

Notice the scroller there. It's not easy to identify on a Mac, but on windows/linux with default scrollers, its pretty weird.

**Comment by robincsamuel** [comment]
Also, can you add my screen to showcase ? url is http://robinz.in

**Comment by Kikobeats** [comment]
I refactored your branch to avoid css inline and user an user a new `main.expanded` class.

Update your ghost version because `.main` is now native HTML5 `main` element.

Yeah, I will add your blog. Thanks for the PR :-)

**Comment by Kikobeats** [comment]
I don't know what I did but I merged the branch but PR not be merged, lol

**Comment by robincsamuel** [comment]
Thanks! Thats okay :)

**Comment by Kikobeats** [comment]
available in `2.3.3` release

**Pull request closed without merging**
