### PR TITLE
added " " to html attributes

### PR DESCRIPTION
**Pull request by AC6567**
done to make theme compatible with ghost 0.8.0

### CODE REVIEW

**Comment by Kikobeats** [comment]
thanks for this!

Just with this change Ghost 0.8 is compatible or it needs more changes?

**Comment by AC6567** [comment]
That should be it. The other two breaking changes aren't relevant on this theme.

**Comment by Kikobeats** [comment]
Nice! I'm going to inspect the rest of the API changes before release a new minor version

**Comment by AC6567** [comment]
Sounds good

**Pull request merged**
